---

## Delete /var/www directory if it exists
- name: Delete /var/www directory
  become: true
  file:
    state: absent
    path: /var/www/

## Create /var/www directory structure
- name: create /var/www
  become: true
  file: path=/var/www state=directory

- name: create /var/www/vhosts
  become: true
  file: path=/var/www/vhosts state=directory

- name: create /var/www/vhosts/{{ domain }}
  become: true
  file: path=/var/www/vhosts/{{ domain }} state=directory

- name: Copies index.html file to remote server
  become: true
  copy: src=files/index.html dest=/var/www/vhosts/{{ domain }}/index.html
