---

## Delete /var/www directory if it exists
- name: Delete /var/www directory
  become: true
  file:
    state: absent
    path: /var/www/

## Create /var/www directory structure
- name: create /var/www
  become: true
  file: path=/var/www state=directory

- name: create /var/www/vhosts
  become: true
  file: path=/var/www/vhosts state=directory

- name: create /var/www/vhosts/projectDir
  become: true
  file: path=/var/www/vhosts/projectDir state=directory

## Download files from github
- name: Download project from folder
  become: true
  git:
    repo: https://github.com/shubhamagarwal1993/pahlakhat.git
    dest: /var/www/vhosts/projectDir

- name: create /var/www/vhosts/{{ domain }}
  become: true
  command: mv /var/www/vhosts/projectDir /var/www/vhosts/{{ domain }}

##- name: Copies index.html file to remote server
##  become: true
##  copy: src=files/index.html dest=/var/www/vhosts/{{ domain }}/index.html

