---
- name: Installs htop
  become: true
  apt: name=htop state=present update_cache=yes cache_valid_time=3600

- name: Installs tmux
  apt: name=tmux state=present update_cache=yes cache_valid_time=3600

- name: Installs vim
  apt: name=vim state=present update_cache=yes cache_valid_time=3600

- name : Installs mosh
  become: true
  apt : name=mosh state=present update_cache=yes cache_valid_time=3600

- name: Copies vimrc file to remote server
  become: true
  copy: src=files/vimrc dest=~/.vimrc mode=0644

- name: Copies tmux.conf file to remote server
  become: true
  copy: src=tmux.conf dest=~/.tmux.conf mode=0644
