---

- name: Update and Upgrade server
  become: true
  apt:
    update_cache: yes
    upgrade: dist
    cache_valid_time: 86400 #One day

- name: install utility packages
  become: true
  apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items:
    - build-essential
    - git
    - nginx
