---

- name: Update and Upgrade server
  become: true
  apt:
    update_cache: yes
    upgrade: dist
    cache_valid_time: 86400 #One day

- name: Install build-essential
  become: true
  apt: name=build-essential state=present update_cache=yes cache_valid_time=3600
