---

- name: install utility packages
  become: true
  apt: pkg={{ item }} state=present
  with_items:
    - build-essential
    - git
    - wget
    - libpcre3
    - libpcre3-dev
    - openssl
    - libssl-dev

## Zlib - requird to unzip nginx files

##zlib_version: 1.2.11
##downloads_dir: /root/

- name: Installs zlib
  become: true
  get_url:
    url: http://zlib.net/zlib-1.2.11.tar.gz
    dest: "/root/"
    mode: 0644

- name : Unarchive zlib
  become: true
  shell: 'tar xvf /root/zlib-1.2.11.tar.gz -C /root/'

- name: Running ./configure for zlib
  become: true
  command: './configure chdir=/root/zlib-1.2.11'

- name : Run "make" on zlib
  become: true
  command: '"{{ item }}" chdir=/root/zlib-1.2.11'
  with_items:
    - make

- name : Run "make install" on zlib
  become: true
  command: 'make install chdir=/root/zlib-1.2.11'

## Nginx

- name: Download nginx
  become: true
  get_url:
    url: https://nginx.org/download/nginx-1.12.1.tar.gz
    dest: "/root/"

- name: Unarchive nginx
  become: true
  shell: 'tar xvf /root/nginx-1.12.1.tar.gz -C /root/'

## Build nginx from source

- name : Run "./configure" on nginx
  become: true  
  command : './configure --conf-path=/etc/nginx/nginx.conf chdir="/root/nginx-1.12.1"'

- name : Run "make on nginx"
  become: true
  command: '"{{ item }}" chdir=/root/nginx-1.12.1'
  with_items:
    - make

- name : Run "make install" on nginx
  become: true
  command: 'make install chdir=/root/nginx-1.12.1'

- name : Copy "nginx.conf" file
  template : src=nginx.conf dest=/etc/nginx/nginx.conf

## Configure Nginx

#- name : Create sites-available folder
#  file : path=/etc/nginx/sites-available state=directory mode=0755 ??????????
#
#- name : Create sites-enabled folder
#  file : path=/etc/nginx/sites-enabled state=directory mode=0755 ?????????
#
#- name : Configure nginx
#  template : src={{ domain }}.conf dest=/etc/nginx/sites-available/{{ domain }}.conf
#  notify :
#    - restart nginx

















